### ISSUE TITLE
Modify call back seems to be fired twice

### ISSUE THREAD

**Issue by 123avi** [lloydmeta/schwatcher#53] opened 2015-11-02 12:47 UTC
Hi ,
executing the integration test ("should fire the appropriate callback if a monitored file has been modified") and looking at the log and I see that the call back seemed to be fired twice (MonitorActor.scala def withCallbackRegistryMap line 80 log.debug(s"Event $event at path: $path"))
I see this line twice in the log file (although I executed only that test that makes single modification ) 
Event ENTRY_MODIFY at path: /tmp/fakeFile3446038815844601275.log
Event ENTRY_MODIFY at path: /tmp/fakeFile3446038815844601275.log

**Comment by lloydmeta** [comment] 2015-11-02 14:18
Hi there,

Thanks for noticing this. There are a few reasons for this behaviour and it may even be platform JVM implementation:

1. When opening a writer for the file, this may cause the callback to be fired.
2. When writing to the file and closing it, a callback may fire.

On my Mac (Yosemite, Java8), I do get 2 callbacks, one for each of the above. However, if I disable the opening of the file for writing and writing, that test fails (can you confirm), which means that it does check for callback due to opening and closing that file.

Note that when creating a fixture for the test, we set up a few files and mark them to be deleted on JVM exit. This might cause a callback to be fired when the forked test JVM process exits, again depending on the JVM implementation.

**Comment by 123avi** [comment] 2015-11-02 16:13
Thank you for your reply. I tried testing it with several os (windows,
Linux - Ubuntu) and different IDE's (eclipse,  intellij ) that behavior
occurred in all of them. Even more,  the tests became unstable since
sometime we got an Event_MODIFY even where Event_Delete expected.  I will
try working on that. But if you have any ideas, guidelines please share.
Thanks
Avi

**Comment by lloydmeta** [comment] 2015-11-03 01:17
Hi there,

As I mentioned in my previous reply, ENTRY_MODIFY events might be caused by the way the fixtures are set up and the fact that certain events are fired at unintuitive times (e.g. opening a file for writing causes ENTRY_MODIFY to be fired without requiring writing or closing of the file..). 

That said, the tests should not be "unstable" (I take this to mean failing and passing intermittently); if you disable the critical part of the test, even though there are other events being fired (due to aforementioned reasons), the tests should not pass. Can you describe what you mean by unstable?

**Comment by 123avi** [comment] 2015-11-03 05:02
Hi ,
by "unstable" I mean that in some machines / IDE's tests might fail due to
getting ENTRY_MODIFY event while expecting EVENT_CREATE .
the following test failed (eclipse on windows):

  describe("integration testing") {
.....

    it("should fire the appropriate callback if a monitored directory has a
directory created inside of it") {
      new Fixtures {
        val register = RegisterCallback(ENTRY_CREATE, None, recursive =
false, tempDirPath,
          path => testActor ! s"New thing at $path")
        monitorActorRef ! register
        // Sleep to make sure that the Java WatchService is monitoring the
file ...
        Thread.sleep(1000)
        val newDir = new File(s"${tempDirPath.toAbsolutePath}/a-new-dir")
        newDir.mkdir()
        // Within 60 seconds is used in case the Java WatchService is
acting slow ...
        within(60 seconds) {
          expectMsg(s"New thing at ${newDir.toPath}")
        }
      }
    }

  }
got this message :
[31m- should fire the appropriate callback if a monitored directory has a
directory created inside of it *** FAILED ***[0m
[31m  java.lang.AssertionError: assertion failed: expected New thing at
C:\Users\victor\AppData\Local\Temp\root1468297180038044736\a-new-dir, found
Modified file is at
C:\Users\victor\AppData\Local\Temp\fakeFile3672545059961629403.log[0m
[31m  at scala.Predef$.assert(Predef.scala:165)[0m
[31m  at
akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:351)[0m
[31m  at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)[0m
[31m  at akka.testkit.TestKit.expectMsg(TestKit.scala:735)[0m
[31m  at
io.equalum.agent.read.filesystem.MonitorActorSpec$$anonfun$3$$anonfun$apply$mcV$sp$31$$anon$20$$anonfun$19.apply(MonitorActorSpec.scala:388)[0m
[31m  at
io.equalum.agent.read.filesystem.MonitorActorSpec$$anonfun$3$$anonfun$apply$mcV$sp$31$$anon$20$$anonfun$19.apply(MonitorActorSpec.scala:388)[0m
[31m  at akka.testkit.TestKitBase$class.within(TestKit.scala:308)[0m
[31m  at akka.testkit.TestKit.within(TestKit.scala:735)[0m
[31m  at akka.testkit.TestKitBase$class.within(TestKit.scala:322)[0m
[31m  at akka.testkit.TestKit.within(TestKit.scala:735)[0m
[31m  ...[0m

here the workaround was simple just replacing the tests location . i.e
executing the "CREATE" test after the "MODIFY" test.
another test that failed :
[32m  for multiple WatchKind.Events[0m
[31m  - should cause all registered event kinds to be detectable for a
path *** FAILED ***[0m
[31m    ENTRY_MODIFY was not equal to ENTRY_DELETE
(WatchServiceTaskSpec.scala:244)[0m

I did found a workaround (not sure it is a correct workaround) here also by
separating the watchkey to two separate watch keys one for each watched
event (i,e CREATE, MODIFY)

Best
Avi



2015-11-03 3:17 GMT+02:00 Lloyd <notifications@github.com>:

**Comment by lloydmeta** [comment] 2015-11-03 08:33
Interesting; having tests intermittently fail is definitely odd..

**Comment by lloydmeta** [comment] 2015-11-03 08:37
Hopefully I'll have time to take a look at this in the future, but at the moment, it seems like on my machine  and on Travis, the lib is performing as expected with regards to the tests.

If you have any new findings please do let me know.

**Comment by 123avi** [comment] 2015-11-06 10:37
Sure I will.
For now like I wrote change the sequence of the tests was enough. I must
say that you did a very impressive work with the tests . It is really top
notch and I learned from it.
BTW why the watch service has to be run as a thread?
Best wishes
Avi

**Comment by lloydmeta** [comment] 2015-11-06 12:36
@123avi the watch service does not absolutely need to be run as a thread, but because of the way the API is set up (you need to take from it and check for events, in an event loop), the simplest and most lightweight pattern is to have an event loop -like thing running inside a thread.

**Comment by 123avi** [comment] 2015-11-09 09:07
Thanks , I did implement the WatchService using actor , it is actually
working quite good . you might want to take a look at the WatchServiceActor
<https://bitbucket.org/avilevi/pathmonitor/src/594bd7b9af6cfc2f220313ff70024f8f9c945655/src/main/scala/org/avi/monitor/WatchServiceActor.scala?at=master>
again,
many thanks , your project was a great help
Avi

2015-11-06 14:36 GMT+02:00 Lloyd <notifications@github.com>:

**Comment by lloydmeta** [comment] 2015-11-23 07:45
Ugh, so I did some more testing of this over the weekend as I was preparing to release a new version to bump dependencies.

Turns out that double MODIFY callbacks is a common thing, caused by non-human updates. See http://stackoverflow.com/questions/16777869/java-7-watchservice-ignoring-multiple-occurrences-of-the-same-event

**Comment by lloydmeta** [comment] 2015-11-23 07:45
Closing for now.

**Closed by lloydmeta** 2015-11-23 07:45 UTC
Labels: investigate, question
