### ISSUE TITLE
The watchers do not work

### ISSUE THREAD

**Issue by Khalian** [lloydmeta/schwatcher#64] opened 2016-09-25 19:47 UTC
``` scala
    package actors

    import java.nio.file.{Path, Paths}
    import java.nio.file.StandardWatchEventKinds._

    import com.beachape.filemanagement.Messages._
    import com.beachape.filemanagement.MonitorActor
    import com.beachape.filemanagement.RegistryTypes._
    import datastructures.ChangedDir

    /**
      * Created by arunavs on 9/25/16.
      */
     class FSWatchImproved(dirs:List[String]) extends MonitorActor {

        val changedCallback: Callback = { path => sendChangedDirMsg(path)}

         // Create a paths list from a dirs list
        val paths = dirs.map(f => Paths get f)

       def sendChangedDirMsg(path:Path): Unit = {
           self ! ChangedDir(path)
       }

       // Register callback for each path create
       paths.foreach(dir => self ! RegisterCallback(
       event = ENTRY_CREATE,
       path = dir ,
       callback =  changedCallback
      ))

      // Register callback for each path create
      paths.foreach(dir => self ! RegisterCallback(
      event = ENTRY_MODIFY,
      path = dir ,
      callback =  changedCallback
      ))

      // Register callback for each path create
      paths.foreach(dir => self ! RegisterCallback(
      event = ENTRY_DELETE,
      path = dir ,
      callback =  changedCallback
     ))
  }

    class FsWatchImprovedTest extends TestKit(ActorSystem("FSWatchTest")) with ImplicitSender
    with WordSpecLike with Matchers with BeforeAndAfterAll with BeforeAndAfterEachTestData {

      val locationDir = "./src/test/data"
      val locationDirFileHandle = new File(locationDir)
      val allLocs = List("./src/test/data", "./src/test/permdata");
      val actorRef = TestActorRef(new FSWatchImproved(allLocs))

      override def afterAll {
        TestKit.shutdownActorSystem(system)
      }

      override def beforeEach(testData: TestData): Unit = {
        locationDirFileHandle.mkdir()
      }

      override def afterEach(testData: TestData): Unit = {
        FileUtils.deleteDirectory(locationDirFileHandle)
      }

      "An FSWatchImproved actor" must {
        "send a changed Dir Message" in {
          val newFileName = "newFile.txt"
          val newFile = new File(locationDir + File.separator + newFileName)
          printTestToFile(newFile)
          expectMsg(ChangedDir(Paths get locationDir))
        }
      }

      def printTestToFile(file:File): Unit = {
        val pw = new PrintWriter(file)
        pw.write("Hello, world")
        pw.close()
      }
    }
```

Expect msg does not work. Test Actor systems time out in 3 seconds.

**Comment by lloydmeta** [comment] 2016-09-26 03:56
Hi there,

Thanks for your report. In my testing, the crux of the issue is solved by replacing `expectMsg(ChangedDir ...` with the following:

```scala
within(60.seconds) {
  val filePath = newFile.getCanonicalFile.toPath
  expectMsg(ChangedDir(filePath))
}
```

Allows the test to pass. This is because of a few reasons:

1. There is generally an over head from the Java FileMonitoring service that is platform independent (might be able to tweak this with modifiers), and the default timeout of expectMsg and friends is not high enough.
2. The path of the file that we receive back from the Java FileMonitoring service is canonical, so we need to make sure we set our test to expect a canonical path.
3. As you see in the code below, we need to tell your custom actor to send messages to the implicit actor reference that is provided by the `ImplicitSender` trait

```scala
class CustomFileWatcher(dirs: List[String], sendToActor: ActorRef) extends MonitorActor {

  val changedCallback: Callback = { path =>
    sendChangedDirMsg(path)
  }

  // Create a paths list from a dirs list
  val paths = dirs.map(f => Paths get f).map(_.normalize())

  // Register callback for each path create
  paths.foreach(dir => self ! RegisterCallback(
    event = ENTRY_CREATE,
    path = dir,
    callback = changedCallback
  ))

  // Register callback for each path create
  paths.foreach(dir => self ! RegisterCallback(
    event = ENTRY_MODIFY,
    path = dir,
    callback = changedCallback
  ))

  // Register callback for each path create
  paths.foreach(dir => self ! RegisterCallback(
    event = ENTRY_DELETE,
    path = dir,
    callback = changedCallback
  ))

  private def sendChangedDirMsg(path: Path): Unit = {
    sendToActor ! ChangedDir(path)
  }

}

class FsWatchImprovedTest extends TestKit(ActorSystem("FSWatchTest")) with ImplicitSender
    with WordSpecLike with Matchers with BeforeAndAfterAll with BeforeAndAfterEachTestData {

  val locationDir = "./src/test/data"
  val locationDirFileHandle = new File(locationDir)
  locationDirFileHandle.mkdir()
  locationDirFileHandle.deleteOnExit()
  val allLocs = List("./src/test/data", "./src/test/permdata")
  val customActorRef = TestActorRef(new CustomFileWatcher(allLocs, self)) // <-- note the passing of the `self` reference, where self is the actor for the test suite itself so we can use expectMsg and friends

  override def afterAll {
    TestKit.shutdownActorSystem(system)
  }

  "An FSWatchImproved actor" must {
    "send a changed Dir Message" in {
      val newFileName = "newFile.txt"
      val newFile = new File(locationDir + File.separator + newFileName)
      printTestToFile(newFile)
      within(60.seconds) {
        val filePath = newFile.getCanonicalFile.toPath
        expectMsg(ChangedDir(filePath))
      }
    }
  }

  def printTestToFile(file: File): Unit = {
    val pw = new PrintWriter(file)
    pw.write("Hello, world")
    pw.close()
  }
}
```

Let me know if you have any further questions or other issues.

**Comment by lloydmeta** [comment] 2016-09-27 13:48
Closing now, since there appear to be no issues with Schwatcher.

**Comment by Khalian** [comment] 2016-09-28 03:07
Just the one thing.

 within(60.seconds) {
}

is within a custom method or some import statement that I am missing?

**Comment by lloydmeta** [comment] 2016-09-28 03:13
`within(duration: Duration)` comes from extending `TestKit` I think.

**Comment by lloydmeta** [comment] 2016-09-28 03:14
I just realised theres a `expectMsg[T](max: FiniteDuration, obj: T)` method offered as well, which will do roughly the same thing as wrapping using a `within` block.

**Comment by Khalian** [comment] 2016-09-28 03:17
Ok my bad its within (60 seconds) not 60.seconds

**Comment by lloydmeta** [comment] 2016-09-28 03:19
Ah ok, `Int` to `Duration` conversion does come from an implicit that is imported via `import scala.concurrent.duration._.

**Comment by Khalian** [comment] 2016-09-28 03:21
Ok so I am using the code you wrote as an answer verbatim and still does not work(this time it times out after 60 seconds).

    [info] An FSWatchImproved actor
    [info] - must send a changed Dir Message *** FAILED ***
    [info]   java.lang.AssertionError: assertion failed: timeout (59998450534 nanoseconds)  during expectMsg while waiting for     ChangedDir(/workplace/arunavs/third_party/DevSync/src/test/data/newFile.txt)
    [info]   at scala.Predef$.assert(Predef.scala:170)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:737)
    [info]   at   CustomFileWatchTests$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(CustomFileWatchTests.scala:44)
    [info]   at CustomFileWatchTests$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(CustomFileWatchTests.scala:42)
    [info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:308)
    [info]   at akka.testkit.TestKit.within(TestKit.scala:737)
    [info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:322)
    [info]   at akka.testkit.TestKit.within(TestKit.scala:737) 
 
I am using Mac OS X Version 10.11.6 (El Capitan).

**Comment by Khalian** [comment] 2016-09-28 03:29
Increasing the timeout is not helping either (I increased it upto 5 mins but the message never got received).

Debugging it revealed that my breakpoints on either of the registered callbacks did not hit. 

It could be that FIle System Watcher simply does not work with HFS. I am using Java  version spec: -

    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)  
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by lloydmeta** [comment] 2016-09-28 03:33
Interesting, 60 second should be more than enough and I'm using HFS myself too; same Java version, everything.

Are you sure you're using the code verbatim? Other than the 60 seconds timeout, I've also modified the actor to take an actor ref as the second constructor parameter and to send the `ChangedDir` message to that ref in the callback.

**Comment by Khalian** [comment] 2016-09-28 03:56
Right now this is my code:-

    package actors

    import java.nio.file.{Path, Paths}

    import akka.actor.ActorRef
    import com.beachape.filemanagement.Messages.RegisterCallback
    import com.beachape.filemanagement.MonitorActor
    import com.beachape.filemanagement.RegistryTypes.Callback
    import datastructures.ChangedDir
    import java.nio.file.StandardWatchEventKinds._

    class CustomFileWatcher(dirs: List[String], sendToActor: ActorRef) extends MonitorActor {

      val changedCallback: Callback = { path =>
        sendChangedDirMsg(path)
      }

      // Create a paths list from a dirs list
      val paths = dirs.map(f => Paths get f).map(_.normalize())

      // Register callback for each path create
      paths.foreach(dir => self ! RegisterCallback(
      event = ENTRY_CREATE,
      path = dir,
      callback = changedCallback
      ))

      // Register callback for each path create
       paths.foreach(dir => self ! RegisterCallback(
       event = ENTRY_MODIFY,
       path = dir,
       callback = changedCallback
       ))

       // Register callback for each path create
       paths.foreach(dir => self ! RegisterCallback(
       event = ENTRY_DELETE,
          path = dir,
          callback = changedCallback
          ))

      private def sendChangedDirMsg(path: Path): Unit = {
         sendToActor ! ChangedDir(path)
      }
    }

    import java.io.{File, PrintWriter}

    import actors.CustomFileWatcher
    import akka.actor.ActorSystem
    import akka.testkit.{ImplicitSender, TestActorRef, TestKit}
    import datastructures.ChangedDir
    import org.apache.commons.io.FileUtils
    import org.scalatest._

    import scala.concurrent.duration._

    /**
      * Created by arunavs on 9/27/16.
      */
    class CustomFileWatchTests extends TestKit(ActorSystem("FSWatchTest")) with ImplicitSende    with WordSpecLike with Matchers with BeforeAndAfterAll with BeforeAndAfterEachTestData {
 
      val locationDir = "./src/test/data"
      val locationDirFileHandle = new File(locationDir)
      val allLocs = List("./src/test/data", "./src/test/permdata")
      val customActorRef = TestActorRef(new CustomFileWatcher(allLocs, self)) // <-- note the passing of the `self` reference, where self is the actor for the test suite itself so we can use expectMsg and friends

      override def afterAll {
        TestKit.shutdownActorSystem(system)
      }

      override def beforeEach(testData: TestData): Unit = {
        locationDirFileHandle.mkdir()
      }

      override def afterEach(testData: TestData): Unit = {
        FileUtils.deleteDirectory(locationDirFileHandle)
      }

      "An FSWatchImproved actor" must {
        "send a changed Dir Message" in {
          val newFileName = "newFile.txt"
          val newFile = new File(locationDir + File.separator + newFileName)
          printTestToFile(newFile)
          within(60 seconds) {
            val filePath = newFile.getCanonicalFile.toPath
            expectMsg(ChangedDir(filePath))
          }
        }
      }

       def printTestToFile(file: File): Unit = {
        val pw = new PrintWriter(file)
        pw.write("Hello, world")
        pw.close()
      }

**Comment by lloydmeta** [comment] 2016-09-28 04:17
It looks fine to me; the only difference that Ivan see is how the directory is being created and deleted, which does not look like it would affect things.

I'll take a closer look later today and add a similar test in a PR.

**Comment by lloydmeta** [comment] 2016-09-28 04:22
Oh I see. In your version, the monitor actor is created and callbacks are registered before the directory even exists, because the directory is created in a before each block. When that happens the file watcher service just ends up failing silently. 

Can you try creating the directory before monitoring it?

**Comment by Khalian** [comment] 2016-09-28 04:27
I could try that.

Anyways my original hypothesis is wrong. The travis CI in my client is Debian and it broke.

https://travis-ci.org/Khalian/DevSync/builds/163301459

**Comment by Khalian** [comment] 2016-09-28 04:35
Yep that was the issue. 

import java.io.{File, PrintWriter}

import actors.CustomFileWatcher
import akka.actor.ActorSystem
import akka.testkit.{ImplicitSender, TestActorRef, TestKit}
import datastructures.ChangedDir
import org.scalatest._

import scala.concurrent.duration._

/**
  * Created by arunavs on 9/27/16.
  */
    class CustomFileWatchTests extends TestKit(ActorSystem("FSWatchTest")) with ImplicitSender
  with WordSpecLike with Matchers with BeforeAndAfterAll with BeforeAndAfterEachTestData {

      val locationDir = "./src/test/permdata"
      val locationDirFileHandle = new File(locationDir)
      locationDirFileHandle.deleteOnExit()
      val allLocs = List("./src/test/permdata")
      val customActorRef = TestActorRef(new CustomFileWatcher(allLocs, self)) // <-- note the passing of the `self` reference, where self is the actor for the test suite itself so we can use expectMsg and friends

      override def afterAll {
        TestKit.shutdownActorSystem(system)
      }

      "An FSWatchImproved actor" must {
        "send a changed Dir Message" in {
          val newFileName = "newFile.txt"
          val newFile = new File(locationDir + File.separator + newFileName)
          printTestToFile(newFile)
          within(100 seconds) {
            val filePath = newFile.getCanonicalFile.toPath
            expectMsg(ChangedDir(filePath))
          }
        }
      }

     def printTestToFile(file: File): Unit = {
        val pw = new PrintWriter(file)
        pw.write("Hello, world")
        pw.close()
      }
    }

Thanks a lot. This code works.

**Comment by Khalian** [comment] 2016-09-28 04:36
I can add this as a test case for your codebase. Can you let me know which packages should I update for the same?

**Comment by lloydmeta** [comment] 2016-12-01 17:14
Closing this because #65 was merged

**Closed by lloydmeta** 2016-12-01 17:14 UTC
